### ISSUE TITLE
How to switch the model from davinci to chatgpt which released today?

### ISSUE THREAD

**Issue by jts0926** [Andndre/chatgpt-whatsapp#10]

**Comment by Andndre** [comment]
Hi, jts...

This project was powered by [this](https://github.com/transitive-bullshit/chatgpt-api) repo.. therefore, we must wait for the latest release of the npm package. Once it is released you can simply run `npm install chatgpt`.

At the time I am writing this message, there has already been a release on that repository regarding the implementation of the chatgpt model (`v5.0.0^`).. but the npm package haven't been updated yet.

**Comment by Andndre** [comment]
Closing this now 

https://github.com/Andndre/chatgpt-whatsapp/commit/25d3f545c90487cef344900cfc51851d2032a18f
